---
openapi: 3.0.2
info:
  title: Word Api
  version: 1.0.0
  description: Show word and modified word
paths:
  /word:
    summary: Path used to manage the list of words.
    description: The REST endpoint/path used to list and create zero or more `Word`
      entities.  This path contains a `GET` and `POST` operation to perform the list
      and create tasks, respectively.
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Word'
              examples:
                words:
                  value:
                  - id: b49dee5b-3b26-4b8f-acdc-11033c6ed7ac
                    name: welcome
                    description: simply dummy text of the printing and typesetting
                      industry
                    langCode: en-us
                    sysnonym:
                    - id: b49dee5b-3b26-4b8f-acdc-11033c6ed7ac
                      name: hi
                      description: simply dummy text of the printing and typesetting
                        industry
                      langCode: en-us
                    - id: b49dee5b-3b26-4b8f-acdc-11033c6ed7ac
                      name: Yo
                      description: simply dummy text of the printing and typesetting
                        industry
                      langCode: en-us
                    mean:
                    - id: b49dee5b-3b26-4b8f-acdc-11033c6ed7ac
                      name: xin chao
                      description: simply dummy text of the printing and typesetting
                        industry
                      langCode: vi
                    - id: b49dee5b-3b26-4b8f-acdc-11033c6ed7ac
                      name: chao
                      description: simply dummy text of the printing and typesetting
                        industry
                      langCode: vi
                  - id: b49dee5b-3b26-4b8f-acdc-11033c6ed7ac
                    name: welcome
                    description: simply dummy text of the printing and typesetting
                      industry
                    langCode: en-us
                    sysnonym:
                    - id: b49dee5b-3b26-4b8f-acdc-11033c6ed7ac
                      name: hi
                      description: simply dummy text of the printing and typesetting
                        industry
                      langCode: en-us
                    - id: b49dee5b-3b26-4b8f-acdc-11033c6ed7ac
                      name: Yo
                      description: simply dummy text of the printing and typesetting
                        industry
                      langCode: en-us
                    mean:
                    - id: b49dee5b-3b26-4b8f-acdc-11033c6ed7ac
                      name: xin chao
                      description: simply dummy text of the printing and typesetting
                        industry
                      langCode: vi
                    - id: b49dee5b-3b26-4b8f-acdc-11033c6ed7ac
                      name: chao
                      description: simply dummy text of the printing and typesetting
                        industry
                      langCode: vi
          description: Successful response - returns an array of `Word` entities.
      operationId: getwords
      summary: List All words
      description: Gets a list of all `Word` entities.
    post:
      requestBody:
        description: A new `Word` to be created.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateWordCommand'
            examples:
              WordCommand:
                value:
                  name: welcome
                  description: simply dummy text of the printing and typesetting industry
                  langCode: en-us
                  sysnonym:
                  - name: hi
                    description: simply dummy text of the printing and typesetting
                      industry
                    langCode: en-us
                  - name: Yo
                    description: simply dummy text of the printing and typesetting
                      industry
                    langCode: en-us
                  mean:
                  - name: xin chao
                    description: simply dummy text of the printing and typesetting
                      industry
                    langCode: vi
                  - name: chao
                    description: simply dummy text of the printing and typesetting
                      industry
                    langCode: vi
        required: true
      responses:
        "201":
          description: Successful response.
      operationId: createWord
      summary: Create a Word
      description: Creates a new instance of a `Word`.
  /word/{wordId}:
    summary: Path used to manage a single Word.
    description: The REST endpoint/path used to get, update, and delete single instances
      of an `Word`.  This path contains `GET`, `PUT`, and `DELETE` operations used
      to perform the get, update, and delete tasks, respectively.
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Word'
              examples:
                word:
                  value:
                    id: b49dee5b-3b26-4b8f-acdc-11033c6ed7ac
                    name: welcome
                    description: simply dummy text of the printing and typesetting
                      industry
                    langCode: en-us
                    sysnonym:
                    - id: b49dee5b-3b26-4b8f-acdc-11033c6ed7ac
                      name: hi
                      description: simply dummy text of the printing and typesetting
                        industry
                      langCode: en-us
                    - id: b49dee5b-3b26-4b8f-acdc-11033c6ed7ac
                      name: Yo
                      description: simply dummy text of the printing and typesetting
                        industry
                      langCode: en-us
                    mean:
                    - id: b49dee5b-3b26-4b8f-acdc-11033c6ed7ac
                      name: xin chao
                      description: simply dummy text of the printing and typesetting
                        industry
                      langCode: vi
                    - id: b49dee5b-3b26-4b8f-acdc-11033c6ed7ac
                      name: chao
                      description: simply dummy text of the printing and typesetting
                        industry
                      langCode: vi
          description: Successful response - returns a single `Word`.
      operationId: getWord
      summary: Get a Word
      description: Gets the details of a single instance of a `Word`.
    put:
      requestBody:
        description: Updated `Word` information.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateWordCommand'
            examples:
              WordDTO:
                value:
                  name: welcome
                  description: simply dummy text of the printing and typesetting industry
                  langCode: en-us
                  sysnonym:
                  - name: hi
                    description: simply dummy text of the printing and typesetting
                      industry
                    langCode: en-us
                  - name: Yo
                    description: simply dummy text of the printing and typesetting
                      industry
                    langCode: en-us
                  mean:
                  - name: xin chao
                    description: simply dummy text of the printing and typesetting
                      industry
                    langCode: vi
                  - name: chao
                    description: simply dummy text of the printing and typesetting
                      industry
                    langCode: vi
        required: true
      responses:
        "202":
          description: Successful response.
      operationId: updateWord
      summary: Update a Word
      description: Updates an existing `Word`.
    delete:
      responses:
        "204":
          description: Successful response.
      operationId: deleteWord
      summary: Delete a Word
      description: Deletes an existing `Word`.
    parameters:
    - examples:
        GuiId:
          value: '"b49dee5b-3b26-4b8f-acdc-11033c6ed7ac"'
      name: wordId
      description: A unique identifier for a `Word`.
      schema:
        type: string
      in: path
      required: true
components:
  schemas:
    Morphemes:
      title: Root Type for Morphemes
      description: The basic unit of morphology, are the smallest meaningful unit
        of language
      required: []
      type: object
      properties:
        id:
          description: Unique Id
          type: string
        name:
          description: Name of morphemes
          type: string
        description:
          description: Pattern of narrative development that aims to make vivid a
            place
          type: string
        langCode:
          description: ISO language codes, conforming to the ISO 639-1 standard
          type: string
      example:
        id: b49dee5b-3b26-4b8f-acdc-11033c6ed7ac
        name: hello
        description: Lorem Ipsum is simply dummy text of the printing and typesetting
          industry
        langCode: en-us
    Word:
      title: Root Type for Word
      description: A word of a spoken language can be defined as the smallest sequence
        of phonemes
      type: object
      allOf:
      - required: []
        type: object
        properties:
          id:
            description: Unique Id
            type: string
          name:
            description: name of word
            type: string
          description:
            description: Pattern of narrative development that aims to make vivid
              a place
            type: string
          langCode:
            description: ISO language codes, conforming to the ISO 639-1 standard
            type: string
          sysnonym:
            description: list word with same meaning
            type: array
            items:
              $ref: '#/components/schemas/Word'
          mean:
            description: list words with difference language code
            type: array
            items:
              $ref: '#/components/schemas/Word'
      - $ref: '#/components/schemas/Morphemes'
      example:
        id: b49dee5b-3b26-4b8f-acdc-11033c6ed7ac
        name: hello
        description: Lorem Ipsum is simply dummy text of the printing and typesetting
          industry
        langCode: en-us
        sysnonym:
        - id: b49dee5b-3b26-4b8f-acdc-11033c6ed7ac
          name: hi
          description: Lorem Ipsum is simply dummy text of the printing and typesetting
            industry
          langCode: en-us
        mean:
        - id: b49dee5b-3b26-4b8f-acdc-11033c6ed7ac
          name: xin chao
          description: Lorem Ipsum is simply dummy text of the printing and typesetting
            industry
          langCode: vi
    CreateWordCommand:
      title: Root Type for CreateWordCommand
      description: Create a Word
      required:
      - mean
      - name
      - langCode
      type: object
      properties:
        name:
          description: Name of word
          type: string
        description:
          description: Pattern of narrative development that aims to make vivid a
            place
          type: string
        langCode:
          description: ISO language codes, conforming to the ISO 639-1 standard
          type: string
        sysnonym:
          description: List a word same meaning in same langugae code
          type: array
          items:
            $ref: '#/components/schemas/Word'
        mean:
          description: List a word same meaning in different langugae code
          type: array
          items:
            $ref: '#/components/schemas/Word'
      example:
        name: welcome
        description: simply dummy text of the printing and typesetting industry
        langCode: en-us
        sysnonym:
        - id: b49dee5b-3b26-4b8f-acdc-11033c6ed7ac
          name: hi
          description: simply dummy text of the printing and typesetting industry
          langCode: en-us
        - id: b49dee5b-3b26-4b8f-acdc-11033c6ed7ac
          name: Yo
          description: simply dummy text of the printing and typesetting industry
          langCode: en-us
        mean:
        - id: b49dee5b-3b26-4b8f-acdc-11033c6ed7ac
          name: xin chao
          description: simply dummy text of the printing and typesetting industry
          langCode: vi
        - id: b49dee5b-3b26-4b8f-acdc-11033c6ed7ac
          name: chao
          description: simply dummy text of the printing and typesetting industry
          langCode: vi
    UpdateWordCommand:
      title: Root Type for UpdateWordCommand
      description: Command update a word
      required:
      - Id
      - langCode
      type: object
      properties:
        name:
          description: Name of word
          type: string
        description:
          description: Pattern of narrative development that aims to make vivid a
            place
          type: string
        langCode:
          description: ISO language codes, conforming to the ISO 639-1 standard
          type: string
        sysnonym:
          description: List a word same meaning in same langugae code
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              description:
                type: string
              langCode:
                type: string
        mean:
          description: List a word same meaning in different langugae code
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              description:
                type: string
              langCode:
                type: string
        Id:
          description: Unique Id
          type: string
      example:
        id: b49dee5b-3b26-4b8f-acdc-11033c6ed7ac
        name: welcome
        description: simply dummy text of the printing and typesetting industry
        langCode: en-us
        sysnonym:
        - id: b49dee5b-3b26-4b8f-acdc-11033c6ed7ac
          name: hi
          description: simply dummy text of the printing and typesetting industry
          langCode: en-us
        - id: b49dee5b-3b26-4b8f-acdc-11033c6ed7ac
          name: Yo
          description: simply dummy text of the printing and typesetting industry
          langCode: en-us
        mean:
        - id: b49dee5b-3b26-4b8f-acdc-11033c6ed7ac
          name: xin chao
          description: simply dummy text of the printing and typesetting industry
          langCode: vi
        - id: b49dee5b-3b26-4b8f-acdc-11033c6ed7ac
          name: chao
          description: simply dummy text of the printing and typesetting industry
          langCode: vi
