---
openapi: 3.0.2
info:
  title: Word Api
  version: 1.0.0
  description: Show word and modified word
  contact:
    name: Tommy Dang
    email: sinhvienbk13@gmail.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
paths:
  /words:
    summary: Path used to manage the list of words.
    description: The REST endpoint/path used to list and create zero or more `Word`
      entities.  This path contains a `GET` and `POST` operation to perform the list
      and create tasks, respectively.
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Word'
              examples:
                words:
                  value:
                  - id: b49dee5b-3b26-4b8f-acdc-11033c6ed7ac
                    name: hello
                    description: Lorem Ipsum is simply dummy text of the printing
                      and typesetting industry
                    langCode: en-us
                  - id: b49dee5b-3b26-4b8f-acdc-11033c6ed7ac
                    name: hi
                    description: Lorem Ipsum is simply dummy text of the printing
                      and typesetting industry
                    langCode: en-us
          description: Successful response - returns an array of `Word` entities.
      operationId: getwords
      summary: List All words
      description: Gets a list of all `Word` entities.
    post:
      requestBody:
        description: A new `Word` to be created.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateWordCommand'
            examples:
              word:
                value:
                  name: hello
                  description: Lorem Ipsum is simply dummy text of the printing and
                    typesetting industry
                  langCode: en-us
        required: true
      responses:
        "201":
          description: Successful response.
      operationId: createWord
      summary: Create a Word
      description: Creates a new instance of a `Word`.
  /words/{wordId}:
    summary: Path used to manage a single Word.
    description: The REST endpoint/path used to get, update, and delete single instances
      of an `Word`.  This path contains `GET`, `PUT`, and `DELETE` operations used
      to perform the get, update, and delete tasks, respectively.
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Word'
              examples:
                word:
                  value:
                    id: b49dee5b-3b26-4b8f-acdc-11033c6ed7ac
                    name: hello
                    description: Lorem Ipsum is simply dummy text of the printing
                      and typesetting industry
                    langCode: en-us
          description: Successful response - returns a single `Word`.
      operationId: getWord
      summary: Get a Word
      description: Gets the details of a single instance of a `Word`.
    put:
      requestBody:
        description: Updated `Word` information.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Word'
            examples:
              word:
                value:
                  id: b49dee5b-3b26-4b8f-acdc-11033c6ed7ac
                  name: hello
                  description: Lorem Ipsum is simply dummy text of the printing and
                    typesetting industry
                  langCode: en-us
        required: true
      responses:
        "202":
          description: Successful response.
      operationId: updateWord
      summary: Update a Word
      description: Updates an existing `Word`.
    delete:
      responses:
        "204":
          description: Successful response.
      operationId: deleteWord
      summary: Delete a Word
      description: Deletes an existing `Word`.
    parameters:
    - examples:
        Id:
          value: '"b49dee5b-3b26-4b8f-acdc-11033c6ed7ac"'
      name: wordId
      description: A unique identifier for a `Word`.
      schema:
        type: string
      in: path
      required: true
components:
  schemas:
    Word:
      title: Root Type for Word
      description: Unit of language
      type: object
      properties:
        id:
          description: Unique Id
          type: string
        name:
          description: Name of Word
          type: string
        description:
          description: Pattern of narrative development that aims to make vivid a
            place
          type: string
        langCode:
          description: ISO language codes, conforming to the ISO 639-1 standard
          type: string
      example:
        id: b49dee5b-3b26-4b8f-acdc-11033c6ed7ac
        name: hello
        description: Lorem Ipsum is simply dummy text of the printing and typesetting
          industry
        langCode: en-us
    CreateWordCommand:
      title: Root Type for CreateWordCommand
      description: Command create a word
      required:
      - name
      - langCode
      type: object
      properties:
        name:
          description: Name of Word
          type: string
        description:
          description: Pattern of narrative development that aims to make vivid a
            place
          type: string
        langCode:
          description: ISO language codes, conforming to the ISO 639-1 standard
          type: string
      example:
        id: b49dee5b-3b26-4b8f-acdc-11033c6ed7ac
        name: hello
        description: Lorem Ipsum is simply dummy text of the printing and typesetting
          industry
        langCode: en-us
    UdpateWordCommand:
      title: Root Type for UdpateWordCommand
      description: Update a word command
      required:
      - id
      - langCode
      - name
      type: object
      properties:
        id:
          description: Unique Id
          type: string
        name:
          description: Name of Word
          type: string
        description:
          description: Pattern of narrative development that aims to make vivid a
            place
          type: string
        langCode:
          description: ISO language codes, conforming to the ISO 639-1 standard
          type: string
      example:
        id: b49dee5b-3b26-4b8f-acdc-11033c6ed7ac
        name: hi
        description: Lorem Ipsum is simply dummy text of the printing and typesetting
          industry
        langCode: en-us
